/* ═══════════════════════════════════════════════════════════════════════════
   TAAL - Passion Partners Beheer in het Engels
   ═══════════════════════════════════════════════════════════════════════════
   Gerrit (2 okt 2026): "Passion Partners Beheer moet volledig Engels zijn als
   de Engelse taal wordt aangezet." Deze woordenlijst hoort bij
   dealerportaal.html en wordt na taal.js geladen; hij vult de algemene
   woordenlijst aan met alle teksten van Beheer. Werkt precies als taal.js:
   alleen tekst die letterlijk hier staat wordt vervangen, dus namen,
   modellen en bedragen blijven ongemoeid.

   Aanvullen: open Beheer met EN aan en tik fpTaalOntbreekt() in de console.
   OTA: staat in manifest.json.
   ═══════════════════════════════════════════════════════════════════════════ */
(function (global) {
  "use strict";
  if (!global.fpTaal) return;
  var W = {
    "Partner of dealer? Een partner koopt in tegen de partnerprijs en ziet alle documentatie, inclusief de prijslijsten waarin partnerprijs, dealerprijs en consumentenprijs naast elkaar staan. Een dealer koopt in tegen een eigen prijsniveau; die ziet zijn eigen prijslijst, want de andere lijsten laten zien wat een ander betaalt. Op dit moment zijn het allemaal partners en is de dealerprijs een presentatiemiddel dat niemand betaalt (Arno, 4 aug 2026). Kies dus alleen Dealer als er echt een afwijkend prijsniveau geldt.": "Partner or dealer? A partner buys at the partner price and sees all documentation, including the price lists that show partner price, dealer price and consumer price side by side. A dealer buys at their own price level; they see their own price list, because the other lists show what someone else pays. Right now everyone is a partner, and the dealer price is a presentation tool that nobody pays (Arno, 4 Aug 2026). So only choose Dealer when a different price level really applies.",
    "- nog kiezen -": "- choose one -",
    "actief": "active",
    "Bewerken": "Edit",
    "Alle gegevens van deze relatie: afspraken, facturatie, verzending en het debiteurnummer": "All details of this relation: agreements, invoicing, shipping and the customer number",
    "Uitnodiging, inloglink, wachtwoord, blokkeren of verwijderen": "Invitation, login link, password, block or remove",
    "terugdraaien": "reverse",
    "Beheer hier wie er in het": "Manage here who can access the",
    "partnerportaal": "partner portal",
    "kan, welke": ", which",
    "documenten": "documents",
    "partners zien, en waar contactvragen binnenkomen. Adres van": "partners see, and where contact questions arrive. Address of",
    "(het publieke portaal):": "(the public portal):",
    ". Partners zien alleen de totale voorraad - klantnamen en inkoopprijzen blijven intern.": ". Partners only see the total stock - customer names and purchase prices stay internal.",
    "+ Nieuwe dealer of partner": "+ New dealer or partner",
    "Bestaat de relatie al in Logic4? Dan zoek je hem in de kaart op en koppel je het debiteurnummer.": "Is the relation already in Logic4? Then look it up in the card and link the customer number.",
    "Aanvragen zonder aanbetaling - leads (": "Requests without a deposit - leads (",
    "Partners die een reservering startten en nog op de": "Partners who started a reservation and whose",
    "aanbetaling": "deposit",
    "staan. Dit zijn aanvragen: ze claimen voorraad zodra de aanbetaling binnen is en staan dan in Logic4. Bel na of archiveer ze.": "is still open. These are requests: they claim stock as soon as the deposit is in, and then they appear in Logic4. Give them a call or archive them.",
    "toon gearchiveerd": "show archived",
    "alleen mijn leads": "only my leads",
    "Alles selecteren": "Select all",
    "niets geselecteerd": "none selected",
    "Geselecteerde verwijderen": "Delete selected",
    "Adviseur": "Adviser",
    "Notitie": "Note",
    "Reserveringen - aanbetaald (": "Reservations - deposit paid (",
    "Partners die": "Partners who",
    "daadwerkelijk hebben aanbetaald": "have actually paid a deposit",
    ". Deze zijn": ". These have been",
    "automatisch": "automatically",
    "als order in Logic4 gezet en claimen voorraad - hier kijk je alleen mee.": "placed as an order in Logic4 and claim stock - here you simply follow along.",
    "Aanbetaling": "Deposit",
    "Logic4-order": "Logic4 order",
    "Annuleringen nakijken": "Check cancellations",
    "Een andere order terugdraaien": "Reverse another order",
    "Vul het Logic4-ordernummer in. Staat er een aanbetaling op die tegengeboekt moet worden, vul dan ook het bedrag in; laat je dat leeg, dan wordt de order alleen geannuleerd.": "Enter the Logic4 order number. If it has a deposit that needs to be reversed, enter the amount too; leave it empty and the order is only cancelled.",
    "Terugdraaien": "Reverse",
    "klik om de lijst te openen": "click to open the list",
    "Bedrijf": "Company",
    "Debiteurnr(s)": "Customer no(s).",
    "(komma-gescheiden)": "(comma-separated)",
    "Regio/valuta": "Region/currency",
    "Soort": "Type",
    "Afspraken": "Agreements",
    "- partner of dealer? -": "- partner or dealer? -",
    "+ Partner toevoegen": "+ Add partner",
    "Welkomstmail aan bestaande relaties": "Welcome e-mail to existing relations",
    "Deze knop is alleen voor de dag dat we": "This button is only for the day we",
    "officieel live gaan met Passion Partners": "officially go live with Passion Partners",
    ". Tot die tijd blijft hij staan zoals hij staat.": ". Until then it stays just as it is.",
    "Iedereen de welkomstmail sturen": "Send everyone the welcome e-mail",
    "Pauzeren": "Pause",
    "Weer verder": "Resume",
    "Wisselkoers EUR/USD": "Exchange rate EUR/USD",
    "De partnerprijzen zijn in dollars. Voor EU-partners rekent het portaal om naar euro's:": "Partner prices are in dollars. For EU partners the portal converts to euros:",
    "€ = $ ÷ koers": "€ = $ ÷ rate",
    ". De koers gaat vanaf nu vanzelf: elke dag wordt de officiële ECB-dagkoers opgehaald en daar gaat": ". From now on the rate updates itself: every day the official ECB daily rate is fetched, and",
    "0,03 vanaf": "0.03 is taken off",
    "(veilige marge). Het bijhouden doet het portaal voor je. BTW komt daarna automatisch uit Logic4 per partner (NL 21%, EU met geldig BTW-nummer 0%, buiten EU 0%).": "(safety margin). The portal keeps track of it for you. VAT then comes automatically from Logic4 per partner (NL 21%, EU with a valid VAT number 0%, outside the EU 0%).",
    "Noodkoers:": "Fallback rate:",
    "Noodkoers opslaan": "Save fallback rate",
    "Partnerprijzen per model (": "Partner prices per model (",
    "klik om alle prijzen te zien": "click to see all prices",
    "Nodig voor de automatische": "Needed for the automatic",
    "30%-aanbetaling": "30% deposit",
    "bij een reservering (Mollie is actief). Zonder prijs blijft een reservering een aanvraag-per-mail. Modelnaam moet exact overeenkomen met de voorraad (bv. \"Renew\"). De": "on a reservation (Mollie is active). Without a price, a reservation stays a request by e-mail. The model name must match the stock exactly (e.g. \"Renew\"). The",
    "artikelcode": "item code",
    "(optioneel) zorgt dat de automatische Logic4-order een echte productregel krijgt in plaats van alleen een omschrijving.": "(optional) gives the automatic Logic4 order a real product line instead of just a description.",
    "Partnerprijs (€, excl. opties)": "Partner price (€, excl. options)",
    "30% aanbetaling": "30% deposit",
    "Artikelcode": "Item code",
    "+ Prijs opslaan": "+ Save price",
    "Modellen en kleuren uit Logic4": "Models and colours from Logic4",
    "Nieuwe modellen en kleuren die in Logic4 worden aangemaakt, komen vanzelf in Passion Partners: vier keer per dag haalt het portaal de lijst op. Een": "New models and colours created in Logic4 appear in Passion Partners by themselves: the portal fetches the list four times a day. A",
    "nieuwe kleur": "new colour",
    "van een bestaand model staat er dan meteen in. Een": "of an existing model shows up right away. A",
    "nieuw model": "new model",
    "verschijnt zodra je hierboven bij Partnerprijzen een prijs invult.": "appears as soon as you enter a price under Partner prices above.",
    "Nu ophalen uit Logic4": "Fetch from Logic4 now",
    "Bibliotheek - bestanden voor partners (": "Library - files for partners (",
    "Dit is wat partners in het portaal onder": "This is what partners see in the portal under",
    "Documenten": "Documents",
    "zien, in precies deze volgorde. Zet hier je pdf, handleiding of afbeelding neer; hij staat er meteen in. Toegestaan: pdf, word, excel, jpg, png en webp, tot 24 MB per bestand.": ", in exactly this order. Put your pdf, manual or image here; it appears right away. Allowed: pdf, word, excel, jpg, png and webp, up to 24 MB per file.",
    "Staat er iets verkeerd?": "Something in the wrong place?",
    "Sleep een regel naar zijn plek (of gebruik de pijltjes), kies een andere map bij": "Drag a line to its place (or use the arrows), choose another folder under",
    "verplaats naar": "move to",
    ", of gooi hem weg met het prullenbakje. Elke wijziging is meteen zichtbaar voor partners.": ", or throw it away with the bin icon. Every change is visible to partners right away.",
    "Titel voor de partner": "Title for the partner",
    "Bestand": "File",
    "Naar het portaal zetten": "Put on the portal",
    "Sleep foto's en bestanden hierheen": "Drag photos and files here",
    "of klik om ze te kiezen. Zoveel als je wilt in één keer.": "or click to choose them. As many as you like at once.",
    "Een foto met het model en de kleur in de naam (bijvoorbeeld": "A photo with the model and the colour in its name (for example",
    "of": "or",
    ") staat meteen bij die kleur, voor alle uitvoeringen. Andere bestanden gaan in de map hierboven.": ") goes straight to that colour, for all versions. Other files go into the folder above.",
    "Foto's ook als download in de map hierboven zetten": "Also put photos as a download in the folder above",
    "Alle mappen openklappen": "Expand all folders",
    "Foto per kleur (partnerportaal)": "Photo per colour (partner portal)",
    "In het portaal ziet een partner bij het reserveren een foto van de spa. Gaat hij met de muis over een kleur, dan wisselt de foto naar die kleur - als hier een foto voor staat. Zonder foto blijft de gewone modelfoto staan met \"photo in this colour to follow\". Kies een model, zet bij elke kleur een foto neer (jpg, png of webp; wordt automatisch verkleind).": "In the portal, a partner sees a photo of the spa when reserving. When they hover over a colour, the photo switches to that colour - when a photo has been added here. Until then, the regular model photo stays with \"photo in this colour to follow\". Choose a model and add a photo for each colour (jpg, png or webp; resized automatically).",
    "kies een model…": "choose a model…",
    "Instellingen": "Settings",
    "Contactvragen van partners gaan naar:": "Contact questions from partners go to:",
    "E-mail nakijken": "Check e-mail",
    "Controleer of de mail eruit kan voordat je een dealer uitnodigt of een aanbetaling verstuurt. Hieronder staan ook de laatste verzendingen met wat Resend erop antwoordde.": "Check that e-mail can go out before you invite a dealer or send a deposit link. Below you also see the latest sends, with what Resend replied.",
    "Mail nakijken": "Check mail",
    "Ordernummer, bv. 3517369": "Order number, e.g. 3517369",
    "Aanbetaling (optioneel)": "Deposit (optional)",
    "zoek op naam, e-mail, debiteurnummer of land…": "search by name, e-mail, customer number or country…",
    "Bedrijfsnaam": "Company name",
    "debiteurnr(s), verplicht": "customer no(s)., required",
    "Wordt gebruikt zodra de automatische dagkoers een keer overslaat": "Used whenever the automatic daily rate skips a day",
    "Model (bv. Renew)": "Model (e.g. Renew)",
    "prijs in €": "price in €",
    "artikelcode (optioneel)": "item code (optional)",
    "bv. Handleiding Passion Wonder": "e.g. Passion Wonder manual",
    "Sleep foto's of bestanden hierheen of klik om ze te kiezen": "Drag photos or files here or click to choose them",
    "zoek in de bibliotheek…": "search the library…",
    "wacht op betaling (expired)": "awaiting payment (expired)",
    "Archiveren": "Archive",
    "geannuleerd in Logic4": "cancelled in Logic4",
    "Selecteer deze aanvraag": "Select this request",
    "ECB-koers van vrijdag 2 oktober": "ECB rate of Friday 2 October",
    "− 0,03 = koers": "- 0.03 = rate",
    ". Voorbeeld: $ 3.349 ÷ 1.0998 = € 3045 (excl. BTW).": ". Example: $ 3,349 ÷ 1.0998 = € 3045 (excl. VAT).",
    "staat klaar als reserve (automatische koers actief)": "ready as backup (automatic rate active)",
    "Nog niet automatisch opgehaald. Klik op de knop om het nu te doen.": "Waiting for the first automatic fetch. Click the button to do it now.",
    "dealers en partners staan klaar in het portaal en wachten op hun welkomstmail. Druk je op de knop, dan krijgen ze de gewone welkomstmail, 70 per dag (dat is de ruimte die de mail per dag heeft). Klaar in ongeveer 7 dagen. Wie zelf al een wachtwoord koos, slaat hij over.": "dealers and partners are ready in the portal, waiting for their welcome e-mail. Press the button and they get the regular welcome e-mail, 70 per day (the most the mail can send in a day). Done in about 7 days. Anyone who already chose a password is skipped.",
    "Ophalen…": "Fetching…",
    "Koers van vandaag wordt opgehaald…": "Fetching today's rate…",
    "Voorbeeld: $ 3.349 ÷ 1.11 = € 3017 (excl. BTW)": "Example: $ 3,349 ÷ 1.11 = € 3017 (excl. VAT)",
    "verplaats naar…": "move to…",
    "Sleep om te verplaatsen": "Drag to move",
    "Eén omhoog": "Move up",
    "Eén omlaag": "Move down",
    "Naar een andere map": "To another folder",
    "Weggooien": "Remove",
    "geen": "none",
    "foto kiezen": "choose photo",
    "Alle mappen dichtklappen": "Collapse all folders",
    "0 van 18 kleuren met foto": "0 of 18 colours with a photo",
    "Foto": "Photo",
    "Kleur": "Colour",
    "Laden…": "Loading…",
    "Uitnodiging sturen": "Send invitation",
    "Inloglink maken": "Create login link",
    "Wachtwoord zetten": "Set password",
    "Adviseur kiezen (Chantal)": "Choose adviser (Chantal)",
    "Blokkeren": "Block",
    "Stuur de welkomstmail: een nette uitnodiging waarmee deze relatie zelf een wachtwoord kiest en meteen ingelogd het portaal in gaat. De link is 7 dagen geldig en kan tegen mailscanners: pas het instellen van het wachtwoord verbruikt hem.": "Send the welcome e-mail: a tidy invitation with which this relation chooses their own password and goes straight into the portal, logged in. The link is valid for 7 days and is safe from mail scanners: only setting the password uses it up.",
    "Genereer een inloglink zonder mail - voor onboarding via WhatsApp of zodra de mail uitblijft. 7 dagen geldig, eenmalig, en sinds 22 aug bestand tegen mailscanners: de link opent eerst een tussenpagina en pas de knop daarop logt in.": "Generate a login link without e-mail - for onboarding via WhatsApp or when the e-mail is slow to arrive. Valid for 7 days, single use, and since 22 Aug safe from mail scanners: the link first opens an in-between page, and only the button on it logs in.",
    "Zet zelf een wachtwoord voor dit account, bijvoorbeeld telefonisch door te geven. Meestal kiest de relatie er zelf een via de uitnodiging.": "Set a password for this account yourself, for example to pass on by phone. Usually the relation chooses one through the invitation.",
    "Adviseur van Fonteyn": "Fonteyn adviser",
    "De adviseur krijgt elke mail aan deze relatie in cc en ziet zijn leads in Beheer.": "The adviser gets every e-mail to this relation in cc and sees their leads in Admin.",
    "- geen adviseur -": "- no adviser -",
    "Relatie verwijderen?": "Remove relation?",
    "wordt uit het portaal gehaald. Inloggen kan daarna opnieuw zodra je hem weer toevoegt; een sessie die nu open staat verloopt vanzelf.": "is removed from the portal. Logging in works again as soon as you add them back; a session that is open now expires by itself.",
    "Logic4 blijft zoals hij is.": "Logic4 stays as it is.",
    "verplicht": "required",
    "Straat": "Street",
    "Huisnummer": "House number",
    "Toevoeging": "Addition",
    "Plaats": "City",
    "Land": "Country",
    "overig": "other",
    "Nieuwe dealer of partner": "New dealer or partner",
    "Wat voor relatie is dit": "What kind of relation is this",
    "Kies eerst partner of dealer. Dat bepaalt welke prijzen en welke documenten deze relatie te zien krijgt.": "First choose partner or dealer. That decides which prices and which documents this relation gets to see.",
    "Koopt in tegen de partnerprijs. Ziet alle prijslijsten en documentatie.": "Buys at the partner price. Sees all price lists and documentation.",
    "Eigen prijsafspraken. Ziet alleen zijn eigen prijzen.": "Own price agreements. Sees only their own prices.",
    "Regio en valuta": "Region and currency",
    "EU - het portaal opent in euro's": "EU - the portal opens in euros",
    "US - het portaal opent in dollars": "US - the portal opens in dollars",
    "- kies de adviseur -": "- choose the adviser -",
    "Wie is het": "Who is it",
    "Aanhef": "Salutation",
    "nog te bepalen": "to be decided",
    "Dhr.": "Mr",
    "Mevr.": "Ms",
    "Voornaam contactpersoon": "Contact first name",
    "Tussenvoegsel": "Name prefix",
    "Achternaam": "Last name",
    "E-mail (inloggen op het portaal)": "E-mail (portal login)",
    "Telefoon": "Phone",
    "Mobiel": "Mobile",
    "Bron klant": "Customer source",
    "Beurs": "Trade fair",
    "Aanbeveling van een klant": "Referral from a customer",
    "Bestaande relatie": "Existing relation",
    "Zelf benaderd": "Approached by us",
    "Belde ons op": "Called us",
    "Adverteren": "Advertising",
    "Via een collega-dealer": "Via a fellow dealer",
    "Anders": "Other",
    "Inkoopafspraken": "Purchase agreements",
    "Afwijkende afspraken met deze partner, als die er zijn. Blijft dit leeg, dan gelden de gewone partnerprijzen. Bij Bewaren komen deze afspraken in Logic4 bij de klant, in Vrij veld 1. Het portaal rekent er niet mee.": "Special agreements with this partner, if any. Leave this empty and the regular partner prices apply. On Save, these agreements go into Logic4 with the customer, in Free field 1. The portal leaves them out of its calculations.",
    "Korting in procenten": "Discount in percent",
    "Waarop geldt die korting": "What the discount applies to",
    "Betaaltermijn": "Payment term",
    "Overige afspraken": "Other agreements",
    "Facturatie": "Invoicing",
    "Het adres en de gegevens die op de factuur horen. Typ het adres in het zoekveld en de velden vullen zichzelf, met stad en land erbij.": "The address and details that belong on the invoice. Type the address in the search field and the fields fill themselves, with city and country included.",
    "Adres opzoeken": "Look up address",
    "Btw-nummer": "VAT number",
    "KvK of handelsregister": "Chamber of Commerce or trade register",
    "Btw-nummer nakijken bij de EU": "Check VAT number with the EU",
    "Controleer btw-nummer": "Check VAT number",
    "Factuur-e-mail": "Invoice e-mail",
    "Verzending": "Shipping",
    "Waar gaan de spa's heen? Partners zitten over de hele wereld, dus land en incoterm horen hier vast te liggen.": "Where do the spas go? Partners are all over the world, so country and incoterm should be fixed here.",
    "hetzelfde adres als de facturatie": "same address as invoicing",
    "Levervoorwaarde": "Delivery terms",
    "anders": "other",
    "Opmerking bij verzending": "Shipping note",
    "Elke relatie hoort een debiteurnummer te hebben. Zoek de bestaande op, of maak een nieuwe aan.": "Every relation should have a customer number. Look up the existing one, or create a new one.",
    "Debiteurnummer(s), komma-gescheiden": "Customer number(s), comma-separated",
    "Nieuw debiteurnummer aanmaken": "Create new customer number",
    "zoals het op de factuur moet staan": "as it should appear on the invoice",
    "bv. 10": "e.g. 10",
    "bv. alleen op spa's": "e.g. only on spas",
    "bv. 30 dagen, of 30% vooruit": "e.g. 30 days, or 30% upfront",
    "vrije aantekening": "free note",
    "bv. Hoofdweg 12, Apeldoorn - of een buitenlands adres": "e.g. Hoofdweg 12, Apeldoorn - or an address abroad",
    "als die afwijkt": "if different",
    "bv. alleen lossen met kraan": "e.g. unload by crane only",
    "bv. 191923": "e.g. 191923",
    "zoek op nummer, e-mailadres of bedrijfsnaam": "search by number, e-mail address or company name",
    "Een partner koopt in tegen de partnerprijs en ziet alle documentatie, inclusief de prijslijsten met alle prijsniveaus naast elkaar.": "A partner buys at the partner price and sees all documentation, including the price lists with all price levels side by side.",
    "Zeker weten?": "Are you sure?",
    "Deze knop is alleen voor de": "This button is only for the",
    "officiële livegang van Passion Partners": "official go-live of Passion Partners",
    "dealers en partners krijgen dan de welkomstmail waarmee ze zelf een wachtwoord kiezen. Dat gaat vanzelf, 70 per dag, tot iedereen hem heeft. Pauzeren kan onderweg; een verstuurde mail blijft verstuurd.": "dealers and partners will then get the welcome e-mail to choose their own password. This runs by itself, 70 per day, until everyone has it. You can pause along the way; a sent e-mail stays sent.",
    "Gaan we vandaag officieel live?": "Are we officially going live today?",
    "Nee, nog even wachten": "Let's wait a little longer",
    "Ja, we gaan officieel live": "Yes, we're officially going live",
    "Op jouw naam is alles afgehandeld.": "Everything in your name is taken care of.",
    "' vraagt de vorm van": "' needs the format used in",
    "(nog": "(another",
    "). Die springt bij zodra de automatische dagkoers een keer overslaat.": "). It steps in whenever the automatic daily rate skips a day.",
    "). Kies een andere titel.": "). Choose another title.",
    ", jij koos": ", you chose",
    "- noteer het nu, dit is het enige moment waarop het te zien is. Geef het los van de mail door.": "- note it down now, this is the only moment it is visible. Pass it on separately from the e-mail.",
    "- sleep hem daar op zijn plek.": "- drag it into place there.",
    ". Kijk het even na.": ". Please give it a quick check.",
    ". Klik nu nog op Bewaren.": ". Now click Save.",
    ". Verwijderen kan Logic4 niet, en een geboekte order hoort ook niet spoorloos te verdwijnen.": ". Logic4 keeps every order, and a booked order should always leave a trace.",
    ". Wie zelf al een wachtwoord koos, slaat hij over.": ". Anyone who already chose a password is skipped.",
    "> hetzelfde adres als de facturatie": "> same address as invoicing",
    "Aanmaken is blijvend.": "Creating is permanent.",
    "Aanvraag verwijderen?": "Delete request?",
    "Adviseur van": "Adviser for",
    "Afwijkende afspraken met deze partner, als die er zijn. Blijft dit leeg, dan gelden de gewone partnerprijzen.": "Special agreements with this partner, if any. Leave this empty and the regular partner prices apply.",
    "Alle orders lopen nog.": "All orders are still active.",
    "Bestand definitief weggooien?": "Delete file permanently?",
    "Bestand kiezen": "Choose file",
    "Bewaard. De afspraken staan in Logic4 bij debiteur": "Saved. The agreements are in Logic4 with customer",
    "Bezig met": "Working on",
    "Bezig met aanmaken…": "Creating…",
    "Bezig met ophalen…": "Fetching…",
    "Bezig met versturen…": "Sending…",
    "Bezig met verwijderen…": "Deleting…",
    "Bij Bewaren komen deze afspraken in Logic4 bij de klant, in Vrij veld 1. Het portaal rekent er niet mee.": "On Save, these agreements go into Logic4 with the customer, in Free field 1. The portal leaves them out of its calculations.",
    "Bijna klaar - vul nog in:": "Almost done - please fill in:",
    "Btw-nummer (verplicht binnen de EU)": "VAT number (required within the EU)",
    "Chantal en Arno zien deze nieuwe relatie bovenaan hun dashboard.": "Chantal and Arno see this new relation at the top of their dashboard.",
    "Controleer het nummer goed: dit nummer staat op zichzelf.": "Check the number carefully: this order stands on its own.",
    "Controleren vraagt nog een poging:": "Checking needs another try:",
    "Daarmee kiest hij zelf een wachtwoord en kan hij inloggen op Passion Partners. De link is zeven dagen geldig.": "With it, they choose their own password and can log in to Passion Partners. The link is valid for seven days.",
    "De aanbetaling van": "The deposit of",
    "De aanvraag verdwijnt uit de lijst. Dit is blijvend.": "The request disappears from the list. This is permanent.",
    "De geselecteerde aanvragen zonder aanbetaling verdwijnen uit de lijst. Dit is blijvend.": "The selected requests without a deposit disappear from the list. This is permanent.",
    "De link is zeven dagen geldig.": "The link is valid for seven days.",
    "De mail kan eruit.": "The e-mail can go out.",
    "De noodkoers hieronder geldt nu - de automatische dagkoers komt zo weer langs.": "The fallback rate below applies now - the automatic daily rate will be back shortly.",
    "De order gaat in Logic4 op": "In Logic4 the order is set to",
    "De order gaat op": "The order is set to",
    "De verstuurde berichten komen hier te staan.": "Sent messages will appear here.",
    "De voorraad die hiervoor vastzat komt weer vrij.": "The stock that was held for this is released again.",
    "Deze tegel is voor het team dat het partnerportaal beheert.": "This tile is for the team that manages the partner portal.",
    "Dit duurt ongeveer een halve minuut.": "This takes about half a minute.",
    "Dit e-mailadres hoort al bij een andere relatie.": "This e-mail address already belongs to another relation.",
    "Dit e-mailadres staat er al in.": "This e-mail address is already in the list.",
    "Dit gaat in Logic4 zelf.": "This is done in Logic4 itself.",
    "Dit is blijvend.": "This is permanent.",
    "Dit nummer staat bij de EU nog open - kijk het na bij de partner.": "This number is still pending with the EU - check it with the partner.",
    "Dit wordt naar Logic4 gestuurd:": "This is sent to Logic4:",
    "Druk je op de knop, dan krijgen ze de gewone welkomstmail,": "Press the button and they get the regular welcome e-mail,",
    "E-mail (vul een geldig adres in)": "E-mail (enter a valid address)",
    "ECB-koers van": "ECB rate of",
    "Een debiteurnummer is verplicht - zoek het bestaande nummer op of maak het eerst aan via de relatiekaart.": "A customer number is required - look up the existing number or create it first via the relation card.",
    "Een e-mailadres is nodig, daarmee logt de relatie in op het portaal.": "An e-mail address is needed; the relation uses it to log in to the portal.",
    "Er gaat een mail naar": "An e-mail goes to",
    "Er is iets mis met de mailinstelling.": "The mail settings need a look.",
    "Er is zojuist een mail gestuurd naar": "An e-mail has just been sent to",
    "Er staat al een bestand met deze naam (": "There is already a file with this name (",
    "Er wordt": "An amount of",
    "Foto voor": "Photo for",
    "Geen nieuwe modellen of kleuren sinds de vorige keer.": "No new models or colours since last time.",
    "Geen openstaande leads.": "All leads are taken care of.",
    "Het geld wordt": "The money is",
    "Hier komen de treffers voor “": "Results for “",
    "Hier komt het adres voor “": "The address for “",
    "Hiermee ben je klaar. Blijft de mail uit, gebruik dan de knop": "That is all you need to do. If the e-mail is slow to arrive, use the button",
    "Inloglink gekopieerd naar je klembord": "Login link copied to your clipboard",
    "Je bent ingelogd als": "You are logged in as",
    "Je hebt gegevens ingevuld die nog op Bewaren wachten. Sluit je dit venster, dan begin je straks opnieuw.": "You have entered details that are still waiting for Save. If you close this window, you will start over later.",
    "Kies een bestand": "Choose a file",
    "Kies een bestand tot 24 MB.": "Choose a file up to 24 MB.",
    "Kies een bestand van je computer.": "Choose a file from your computer.",
    "Kies eerst een map.": "Choose a folder first.",
    "Kies eerst of dit een partner of een dealer is \\u2014 dat bepaalt welke prijslijsten dit account te zien krijgt.": "First choose whether this is a partner or a dealer - that decides which price lists this account gets to see.",
    "Kies eerst partner of dealer.": "First choose partner or dealer.",
    "Klaar": "Done",
    "Klaar - de uitnodiging is onderweg": "Done - the invitation is on its way",
    "Klaar in ongeveer": "Done in about",
    "Klaar.": "Done.",
    "Klaar:": "Done:",
    "Koppel eerst een debiteurnummer: zoek de bestaande relatie op in het blok Logic4 onderaan, of maak daar een nieuw debiteurnummer aan.": "Link a customer number first: look up the existing relation in the Logic4 block at the bottom, or create a new customer number there.",
    "Minstens 8 tekens. Schrijf het over voordat je opslaat: dit is het enige moment waarop het te zien is, ook voor ons. Geef het los van de mail door.": "At least 8 characters. Write it down before you save: this is the only moment it is visible, for us too. Pass it on separately from the e-mail.",
    "Na het aanmaken moet iemand in Logic4 zelf zetten:": "After creating, someone needs to set in Logic4 itself:",
    "Naar": "To",
    "Nakijken vraagt nog een poging:": "Checking needs another try:",
    "Navragen bij de EU…": "Checking with the EU…",
    "Nieuwe kleuren en uitvoeringen": "New colours and versions",
    "Nog controleren.": "Still to check.",
    "Nog geen aanbetaalde reserveringen.": "Paid reservations will appear here.",
    "Ook de nieuwe relaties meenemen": "Include the new relations too",
    "Opgeslagen - de mail wacht nog": "Saved - the e-mail is still waiting",
    "Opgeslagen - partnervragen gaan nu naar": "Saved - partner questions now go to",
    "Ophalen lukte niet.": "Fetching needs another try.",
    "Ophalen vraagt nog een poging:": "Fetching needs another try:",
    "Partner toegevoegd - die kan nu inloggen op het portaal met een magic-link.": "Partner added - they can now log in to the portal with a magic link.",
    "Postcode en plaats": "Postcode and city",
    "Prijs opgeslagen - reserveringen voor": "Price saved - reservations for",
    "Soort relatie (dealer of partner)": "Type of relation (dealer or partner)",
    "Staat op:": "Registered to:",
    "Stuur hem alsnog met de knop": "You can still send it with the button",
    "Terug naar het formulier": "Back to the form",
    "Terugdraaien vraagt nog een poging": "Reversing needs another try",
    "Toegang op aanvraag": "Access on request",
    "Toegang op aanvraag: Gerrit zet je in de groep voor Passion Partners Beheer.": "Access on request: Gerrit adds you to the group for Passion Partners Admin.",
    "Typ eerst een adres om op te zoeken.": "Type an address to look up first.",
    "Voeg de eerste dealer of partner toe.": "Add the first dealer or partner.",
    "Voer een geldige koers in (tussen 0,5 en 2).": "Enter a valid rate (between 0.5 and 2).",
    "Vraagt nog een poging:": "Needs another try:",
    "Vul een bedrag in om iets tegen te boeken.": "Enter an amount to reverse it.",
    "Vul een geldig e-mailadres in.": "Enter a valid e-mail address.",
    "Vul een modelnaam en een prijs > 0 in.": "Enter a model name and a price > 0.",
    "Vul een ordernummer in.": "Enter an order number.",
    "Vul eerst een btw-nummer in.": "Enter a VAT number first.",
    "Waar gaan de spa\\'s heen? Partners zitten over de hele wereld, dus land en incoterm horen hier vast te liggen.": "Where do the spas go? Partners are all over the world, so country and incoterm should be fixed here.",
    "Wachtwoord moet minstens 8 tekens zijn.": "The password needs at least 8 characters.",
    "Wachtwoord voor": "Password for",
    "Weggooien wat je hebt ingevuld?": "Discard what you entered?",
    "Welkomstmail verstuurd naar": "Welcome e-mail sent to",
    "Wijkt er iets af, haal de relatie dan in Logic4 zelf weg.": "If anything differs, remove the relation in Logic4 itself.",
    "Zoeken vraagt nog een poging:": "Searching needs another try:",
    "\\u201d staat in": "\\u201d is in",
    "aanvraag": "request",
    "aanvraag - wacht op aanbetaling": "request - waiting for deposit",
    "aanvraag/aanvragen verwijderd.": "request(s) deleted.",
    "adres(sen) gevonden - klik de juiste aan.": "address(es) found - click the right one.",
    "bestand": "file",
    "bestand groter dan 24 MB": "file larger than 24 MB",
    "betaling nog te boeken": "payment still to be booked",
    "de beheersleutel vraagt om een nieuwe": "the admin key needs renewing",
    "dealers en partners krijgen dan de welkomstmail waarmee ze zelf een wachtwoord kiezen.": "dealers and partners will then get the welcome e-mail to choose their own password.",
    "dealers en partners staan klaar in het portaal en wachten op hun welkomstmail.": "dealers and partners are ready in the portal, waiting for their welcome e-mail.",
    "deze relatie": "this relation",
    "een sessie die nu open staat verloopt vanzelf.": "a session that is open now expires by itself.",
    "een wachtwoord en kan": "a password and can",
    "en is meteen zichtbaar voor partners.": "and is visible to partners right away.",
    "en nog": "and",
    "foto weghalen": "remove photo",
    "geeft de naam bij een btw-nummer niet vrij, dus die is hier niet te vergelijken.": "keeps the name behind a VAT number private, so there is nothing to compare here.",
    "heeft nu geen adviseur.": "now has no adviser.",
    "hij": "he",
    "in de lijst.": "in the list.",
    "in de lijst. Zodra": "in the list. As soon as",
    "in de rij": "in the queue",
    "kan nu inloggen met wachtwoord:": "can now log in with password:",
    "kies de kleur": "choose the colour",
    "kies een afbeelding": "choose an image",
    "kies eerst een map": "choose a folder first",
    "kies het model en de kleur": "choose the model and the colour",
    "kies model en kleur": "choose model and colour",
    "klaar": "done",
    "kleuren en uitvoeringen.": "colours and versions.",
    "kleuren met foto": "colours with a photo",
    "koers": "rate",
    "krijgen straks automatisch een 30%-aanbetalingslink.": "will automatically get a 30% deposit link from now on.",
    "naar plek": "to position",
    "niet": "not",
    "nieuwe relaties klaar voor hun welkomstmail.": "new relations ready for their welcome e-mail.",
    "nog geen partnerprijs, dus nog niet zichtbaar": "awaiting a partner price, so hidden for now",
    "nog omzetten naar debiteur": "still to convert to customer",
    "nog te kiezen": "still to choose",
    "per dag (dat is de ruimte die de mail per dag heeft).": "per day (the most the mail can send in a day).",
    "relaties hebben de welkomstmail gekregen.": "relations have received the welcome e-mail.",
    "staat erin als": "is listed as",
    "staat nu op Dealer - dit account ziet voortaan alleen zijn eigen prijzen.": "is now set to Dealer - from now on this account sees only its own prices.",
    "staat nu op Partner \\u2014 dit account ziet alle documentatie.": "is now set to Partner - this account sees all documentation.",
    "toegang op aanvraag": "access on request",
    "uit de zoeklijst van vannacht": "from last night's search list",
    "van": "of",
    "verdwijnt uit het partnerportaal, en het bestand zelf wordt ook verwijderd.": "disappears from the partner portal, and the file itself is deleted too.",
    "verstuurd, nog": "sent, another",
    "voor": "for",
    "vraagt nog een poging:": "needs another try:",
    "wordt aangemaakt…": "being created…",
    "wordt tegengeboekt in dagboek Mollie.": "is reversed in the Mollie journal.",
    "zelf een wachtwoord en kan": "their own password and can",
    "” - probeer een ander zoekwoord.": "” will appear here - try another search term.",
    "” - probeer het met plaatsnaam erbij.": "” will appear here - try adding the city.",
    "” is uit het portaal gehaald.": "” has been removed from the portal.",
    "” staat nu onderaan in": "” is now at the bottom of"
  };
  for (var k in W) if (Object.prototype.hasOwnProperty.call(W, k)) global.fpTaal.woorden[k] = W[k];
  var DAGEN = { maandag: "Monday", dinsdag: "Tuesday", woensdag: "Wednesday", donderdag: "Thursday", vrijdag: "Friday", zaterdag: "Saturday", zondag: "Sunday" };
  var MAANDEN = { januari: "January", februari: "February", maart: "March", april: "April", mei: "May", juni: "June", juli: "July", augustus: "August", september: "September", oktober: "October", november: "November", december: "December" };
  var P = global.fpTaal.patronen;
  P.push([/^live · bijgewerkt (\d{1,2}:\d{2}(?::\d{2})?)$/, "live · updated $1"]);
  P.push([/^ECB-koers van (\w+) (\d{1,2}) (\w+)(, opgehaald (.+))?$/, function (m, d, n, mnd, x, op) { return "ECB rate of " + (DAGEN[d] || d) + " " + n + " " + (MAANDEN[mnd] || mnd) + (op ? ", fetched " + op : ""); }]);
  P.push([/^adviseur (.+)$/, "adviser $1"]);
  P.push([/^Adviseur kiezen \((.+)\)$/, "Choose adviser ($1)"]);
  P.push([/^(\d+) gevonden$/, "$1 found"]);
  P.push([/^(\d+) geselecteerd$/, "$1 selected"]);
  P.push([/^Verwijder (\d+) aanvragen?$/, function (m, n) { return "Delete " + n + (n === "1" ? " request" : " requests"); }]);
  P.push([/^(\d+) van (\d+) kleuren met foto$/, "$1 of $2 colours with a photo"]);
  P.push([/^(\d+) van (\d+) staan erin$/, "$1 of $2 are in"]);
  P.push([/^(\d+) bezig…$/, "$1 in progress…"]);
  P.push([/^(\d+) wachten op een keuze$/, "$1 waiting for a choice"]);
  P.push([/^Adviseur van (.+)$/, "Adviser of $1"]);
})(typeof window !== "undefined" ? window : globalThis);
